[package]
name = "tc_rc_cipher"
description = "RC2, RC5 and RC6 block ciphers."
version.workspace = true
edition.workspace = true
rust-version = "1.85"
license.workspace = true
repository.workspace = true

[features]
default = []
rustcrypto = ["dep:rc2", "rc2/zeroize", "dep:rc5", "dep:rc6"]

[dependencies]
tc_block_cipher = "0.1.0"
tc_zeroize = "0.1.0"
rc2 = { version = "0.9.0", optional = true }
rc5 = { version = "0.1.0", optional = true }
rc6 = { version = "0.1.0", optional = true }

