[package]
name = "tc_key_wrap"
description = "Key wrapping algorithms over block ciphers."
version.workspace = true
edition.workspace = true
rust-version = "1.85"
license.workspace = true
repository.workspace = true

[dependencies]
rand_core = { workspace = true }
tc_block_cipher = "0.1.0"
tc_zeroize = { version = "0.1.0", features = ["alloc"] }

[dev-dependencies]
tc_aes = "0.1.0"