[package]
name = "tc_aead_cipher"
description = "Authenticated encryption with associated data (AEAD) contracts."
version.workspace = true
edition.workspace = true
rust-version = "1.85"
license.workspace = true
repository.workspace = true

[dependencies]
tc_block_cipher = "0.1.0"
tc_constant_time = "0.1.0"
tc_zeroize = "0.1.0"
