[package]
name = "tc_des_wrap"
description = "CMS Triple-DES key wrapping from RFC 3217 for the tc_rust workspace."
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tc_constant_time = "0.1.0"
rand_core = { workspace = true }
tc_block_cipher = "0.1.0"
tc_des = "0.1.0"
tc_digest = "0.1.0"
tc_key_wrap = { version = "0.1", path = "../tc_key_wrap" }
tc_sha = "0.1.0"
tc_zeroize = { version = "0.1.0", features = ["alloc"] }
